server:
  port: 8080
  servlet:
    context-path: /mail-sink

logging:
  level:
    root: INFO
    org.springframeowrk: INFO
    io.github.koneru9999: TRACE

mailsink:
  dummy-data-size: ${DUMMY_DATA_SIZE: 0} # > 0 for enabling dummy data